### ISSUE TITLE
user id

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-login#16]
მომხმარებელს მხოლოდ სახელი აქვს უნიკალური? userName == userId?

**Comment by slezh12** [comment]
ki

**Comment by slezh12** [comment]
user tu ukve daregistrirebulia mocemuli userName-it ra error code unda davabrunot?409?

**Comment by gkiko** [comment]
სწორს ამბობს [ეს ტიპი](http://stackoverflow.com/a/3826024/660408)
